# Generated by Django 4.1.2 on 2022-10-18 19:08

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='compra',
            name='data_compra',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='compra',
            name='jogo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='compras', to='api.jogo'),
        ),
        migrations.AddField(
            model_name='jogo',
            name='descricao',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='jogo',
            name='imagem',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AddField(
            model_name='jogo',
            name='lojas',
            field=models.CharField(default='', max_length=256),
        ),
        migrations.AddField(
            model_name='jogo',
            name='nome',
            field=models.CharField(default='', max_length=128),
        ),
        migrations.AddField(
            model_name='jogo',
            name='plataformas',
            field=models.CharField(default='', max_length=128),
        ),
        migrations.AddField(
            model_name='jogo',
            name='preco',
            field=models.FloatField(default=0.0),
        ),
    ]
